### ISSUE TITLE
S3_E3 Distance as Stop Criterion

### ISSUE THREAD

**Issue by milsen** [ea5az/machinelearninggroup31#2]
Hey, great work on the last two exercises. I tried it with Python (see my fork)  and at least exercise 2 worked for me but it was extremely slow because I did not have the idea to compute the distance matrix only once at the beginning (mental facepalm). Do you also feel like the machine learning homework is getting somewhat exhausting?

Anyway, concerning exercise 3 it seems to me that you again computed five clusters but the exercise description says that we should use the distance as a stop criterion. So maybe we should take the difference between the last smallest distance and this smallest distance and see whether if goes below some epsilon?

Oh, and yesterday I wasn't able to push to your repository so maybe you haven't added me as a collaborator so far. Or am I missing something?

**Comment by ea5az** [comment]
Oh yep, you are completely right about exercise 3, I'll have to look into that tomorrow (today actually).

I actually really don't know how git works :3 I didn't know there was anything like collaborators, I just added you, sorry for the delay. I also only just now found out what forks are but yep, that looks like it makes sense. I definitely want to look at your code as soon as possible too :)

**Comment by milsen** [comment]
No problem; basically everything I know about git stems from these two websites:
http://rogerdudler.github.io/git-guide/
http://gitref.org/

Oh, and don't look too closely at my code. Honestly, it sucks :/. And I probably don't have the time to improve it today. If I do find some time, I may push a better version to this repo, but your code looks pretty good, anyway, so at the moment I'd just go with all of your solutions this time. 
(Don't forget to zip them up, otherwise all the separate files will clutter up our Stud.IP group folder.)
